[Item1]
Description=p_reservar_id_log_activo
TestScript=p_reservar_id_log_activo.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item2]
Description=p_reservar_id_log_inactivo
TestScript=p_reservar_id_log_inactivo.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item3]
Description=f_id_operacion_existente
TestScript=f_id_operacion_existente.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item4]
Description=f_id_operacion_inexistente
TestScript=f_id_operacion_inexistente.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item5]
Description=f_filtros_sql_sin_parametros
TestScript=f_filtros_sql_sin_parametros.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item6]
Description=f_filtros_sql_parametros_ignorados
TestScript=f_filtros_sql_parametros_ignorados.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item7]
Description=f_filtros_sql_parametro_varchar2
TestScript=f_filtros_sql_parametro_varchar2.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item8]
Description=f_filtros_sql_parametro_date
TestScript=f_filtros_sql_parametro_date.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item9]
Description=f_filtros_sql_parametro_number
TestScript=f_filtros_sql_parametro_number.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item10]
Description=f_filtros_sql_tipo_no_soportado
TestScript=f_filtros_sql_tipo_no_soportado.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item11]
Description=f_valor_parametro_lista_null
TestScript=f_valor_parametro_lista_null.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item12]
Description=f_valor_parametro_lista_vacia
TestScript=f_valor_parametro_lista_vacia.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item13]
Description=f_valor_parametro_nombre_con_diferente_case
TestScript=f_valor_parametro_nombre_con_diferente_case.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item14]
Description=f_valor_parametro_nombre_inexistente
TestScript=f_valor_parametro_nombre_inexistente.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item15]
Description=f_valor_parametro_string
TestScript=f_valor_parametro_string.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item16]
Description=f_valor_parametro_number
TestScript=f_valor_parametro_number.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item17]
Description=f_valor_parametro_boolean
TestScript=f_valor_parametro_boolean.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item18]
Description=f_valor_parametro_date
TestScript=f_valor_parametro_date.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item19]
Description=f_valor_parametro_object
TestScript=f_valor_parametro_object.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK

[Notes]
{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang3082{\fonttbl{\f0\fnil\fcharset0 Arial;}}
{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
\pard\fs20 Tests unitarios del paquete k_operacion\par
}
