name: risk

services:

  database:
    image: jtsoya539/risk-database:latest
    build:
      context: .
      dockerfile: ./Dockerfile.database
    pull_policy: build
    ports:
      - 1521:1521
    env_file:
      - ./docker/database.env

  redis:
    image: redis:alpine

  backend:
    image: jtsoya539/risk-backend:latest
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    pull_policy: build
    ports:
      - 5000:5000
    env_file:
      - ./docker/backend.env
    depends_on:
      - database
      - redis