name: risk

services:

  database:
    image: jtsoya539/risk-database:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      no_cache: true
    pull_policy: build
    ports:
      - 1524:1521

  redis:
    image: redis:alpine

  backend:
    image: jtsoya539/risk-backend:latest
    build:
      context: ./source/backend
      dockerfile: ./Dockerfile
      no_cache: true
    pull_policy: build
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - database
      - redis