name: risk

services:

  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:database
    command: sleep infinity

  database:
    image: jtsoya539/risk-database:latest
    build:
      context: .
      dockerfile: ./Dockerfile.database
      no_cache: true
    pull_policy: build
    ports:
      - 1521:1521

  redis:
    image: redis:alpine

  backend:
    image: jtsoya539/risk-backend:latest
    build:
      context: .
      dockerfile: ./Dockerfile.backend
      no_cache: true
    pull_policy: build
    ports:
      - 5000:5000
    depends_on:
      - database
      - redis