name: risk

services:

  database:
    image: jtsoya539/risk-database:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      no_cache: true
    pull_policy: build
    ports:
      - 1524:1521

  redis:
    image: redis:alpine