[Item1]
Description=f_procesar_servicio_inexistente
TestScript=f_procesar_servicio_inexistente.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item2]
Description=f_procesar_servicio_error_json_parametros
TestScript=f_procesar_servicio_error_json_parametros.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item3]
Description=f_procesar_servicio_error_json_contexto
TestScript=f_procesar_servicio_error_json_contexto.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item4]
Description=f_procesar_servicio_error_tipo_contexto
TestScript=f_procesar_servicio_error_tipo_contexto.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item5]
Description=f_procesar_servicio_version_sistema
TestScript=f_procesar_servicio_version_sistema.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK

[Notes]
{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang3082{\fonttbl{\f0\fnil\fcharset0 Arial;}}
{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
\pard\fs20 Tests unitarios del paquete k_servicio\par
}
