[Item1]
Description=f_tipo_excepcion_ude_negativo
TestScript=f_tipo_excepcion_ude_negativo.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item2]
Description=f_tipo_excepcion_ude_positivo
TestScript=f_tipo_excepcion_ude_positivo.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item3]
Description=f_tipo_excepcion_ope
TestScript=f_tipo_excepcion_ope.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item4]
Description=f_mensaje_excepcion_ude
TestScript=f_mensaje_excepcion_ude.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item5]
Description=f_mensaje_excepcion_ope
TestScript=f_mensaje_excepcion_ope.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item6]
Description=f_mensaje_excepcion_ope_sin_plsql
TestScript=f_mensaje_excepcion_ope_sin_plsql.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item7]
Description=f_mensaje_error_default_wrap_char
TestScript=f_mensaje_error_default_wrap_char.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item8]
Description=f_mensaje_error_custom_wrap_char
TestScript=f_mensaje_error_custom_wrap_char.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item9]
Description=f_mensaje_error_no_registrado
TestScript=f_mensaje_error_no_registrado.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK

[Notes]
{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang3082{\fonttbl{\f0\fnil\fcharset0 Arial;}}
{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
\pard\fs20 Tests unitarios del paquete k_error\par
}
