[Item1]
Description=p_guardar_dato_string_uso_basico
TestScript=p_guardar_dato_string_uso_basico.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=
Var1InputValue=
Var1OutputValue=OK
[Item2]
Description=p_guardar_dato_number_uso_basico
TestScript=p_guardar_dato_number_uso_basico.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=
Var1InputValue=
Var1OutputValue=OK
[Item3]
Description=p_guardar_dato_boolean_uso_basico
TestScript=p_guardar_dato_boolean_uso_basico.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=
Var1InputValue=
Var1OutputValue=OK
[Item4]
Description=p_guardar_dato_date_uso_basico
TestScript=p_guardar_dato_date_uso_basico.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=
Var1InputValue=
Var1OutputValue=OK
[Item5]
Description=p_guardar_dato_object_uso_basico
TestScript=p_guardar_dato_object_uso_basico.tst
NewSession=False
Enabled=False
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=
Var1InputValue=
Var1OutputValue=OK

[Notes]
{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang3082{\fonttbl{\f0\fnil\fcharset0 Arial;}}
{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
\pard\fs20 Tests unitarios del paquete k_dato\par
}
