[Item1]
Description=f_valor_parametro_parametro_con_valor
TestScript=f_valor_parametro_parametro_con_valor.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=
Var1InputValue=
Var1OutputValue=OK
[Item2]
Description=f_valor_parametro_parametro_sin_valor
TestScript=f_valor_parametro_parametro_sin_valor.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=
Var1InputValue=
Var1OutputValue=OK
[Item3]
Description=f_valor_parametro_parametro_inexistente
TestScript=f_valor_parametro_parametro_inexistente.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=
Var1InputValue=
Var1OutputValue=OK
[Item4]
Description=p_actualizar_valor_parametro_uso_basico
TestScript=p_actualizar_valor_parametro_uso_basico.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=
Var1InputValue=
Var1OutputValue=OK
[Item5]
Description=f_base_datos
TestScript=f_base_datos.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item6]
Description=f_terminal
TestScript=f_terminal.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item7]
Description=f_host
TestScript=f_host.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item8]
Description=f_direccion_ip
TestScript=f_direccion_ip.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item9]
Description=f_esquema_actual
TestScript=f_esquema_actual.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK

[Notes]
{\rtf1\ansi\ansicpg1252\deff0\deflang3082{\fonttbl{\f0\fnil\fcharset0 Arial;}}
\viewkind4\uc1\pard\fs20 Tests unitarios del paquete k_util\par
}
