prompt Importing table t_rol_permisos...
set feedback off
set define off

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'REPORTE:GEN:LISTAR_SIGNIFICADOS', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'REPORTE:GEN:VERSION_SISTEMA', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:CAMBIAR_CLAVE', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:CAMBIAR_ESTADO_SESION', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:CAMBIAR_ESTADO_USUARIO', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:DATOS_DISPOSITIVO', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:DATOS_USUARIO', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:EDITAR_USUARIO', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:GENERAR_OTP', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:INICIAR_SESION', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:REFRESCAR_SESION', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:REGISTRAR_CLAVE', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:REGISTRAR_DISPOSITIVO', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:REGISTRAR_UBICACION', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:REGISTRAR_USUARIO', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:TIEMPO_EXPIRACION_TOKEN', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:VALIDAR_CLAVE_APLICACION', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:VALIDAR_CREDENCIALES', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:VALIDAR_OTP', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:AUT:VALIDAR_SESION', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:GEN:GUARDAR_ARCHIVO', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:GEN:LISTAR_BARRIOS', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:GEN:LISTAR_CIUDADES', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:GEN:LISTAR_DEPARTAMENTOS', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:GEN:LISTAR_ERRORES', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:GEN:LISTAR_PAISES', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:GEN:LISTAR_SIGNIFICADOS', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:GEN:RECUPERAR_ARCHIVO', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:GEN:RECUPERAR_TEXTO', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:GEN:SIGNIFICADO_CODIGO', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:GEN:VALOR_PARAMETRO', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:GEN:VERSION_SERVICIO', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (2, 'SERVICIO:GEN:VERSION_SISTEMA', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (3, 'SERVICIO:MSJ:CAMBIAR_ESTADO_MENSAJERIA', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (3, 'SERVICIO:MSJ:LISTAR_CORREOS_PENDIENTES', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (3, 'SERVICIO:MSJ:LISTAR_MENSAJES_PENDIENTES', 'N', 'N', 'N', 'N');

insert into t_rol_permisos (ID_ROL, ID_PERMISO, CONSULTAR, INSERTAR, ACTUALIZAR, ELIMINAR)
values (3, 'SERVICIO:MSJ:LISTAR_NOTIFICACIONES_PENDIENTES', 'N', 'N', 'N', 'N');

prompt Done.
