prompt Importing table t_servicios...
set feedback off
set define off
insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (1, 'VALIDAR_CREDENCIALES', 'T', 'S', 'AUT', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (2, 'INICIAR_SESION', 'T', 'S', 'AUT', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (3, 'CAMBIAR_ESTADO_SESION', 'T', 'S', 'AUT', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (4, 'REGISTRAR_USUARIO', 'T', 'S', 'AUT', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (5, 'REGISTRAR_CLAVE', 'T', 'S', 'AUT', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (6, 'CAMBIAR_CLAVE', 'T', 'S', 'AUT', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (7, 'VALIDAR_SESION', 'T', 'S', 'AUT', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (8, 'VALOR_PARAMETRO', 'T', 'S', 'GEN', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (9, 'SIGNIFICADO_CODIGO', 'T', 'S', 'GEN', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (10, 'DATOS_USUARIO', 'T', 'S', 'AUT', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (11, 'REFRESCAR_SESION', 'T', 'S', 'AUT', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (12, 'VALIDAR_CLAVE_APLICACION', 'T', 'S', 'AUT', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (13, 'VERSION_SISTEMA', 'T', 'S', 'GEN', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (14, 'REGISTRAR_DISPOSITIVO', 'T', 'S', 'AUT', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (16, 'LISTAR_PAISES', 'T', 'S', 'GEN', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (17, 'TIEMPO_EXPIRACION_TOKEN', 'T', 'S', 'AUT', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (18, 'RECUPERAR_ARCHIVO', 'T', 'S', 'GEN', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (19, 'GUARDAR_ARCHIVO', 'T', 'S', 'GEN', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (30, 'LISTAR_MENSAJES_PENDIENTES', 'T', 'S', 'MSJ', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (31, 'CAMBIAR_ESTADO_MENSAJE', 'T', 'S', 'MSJ', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (32, 'LISTAR_CORREOS_PENDIENTES', 'T', 'S', 'MSJ', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (33, 'CAMBIAR_ESTADO_CORREO', 'T', 'S', 'MSJ', null, null, null, null);

insert into t_servicios (ID_SERVICIO, NOMBRE, TIPO, ACTIVO, DOMINIO, DETALLE, VERSION_ACTUAL, CANTIDAD_EJECUCIONES, FECHA_ULTIMA_EJECUCION)
values (42, 'EDITAR_USUARIO', 'T', 'S', 'AUT', null, null, null, null);

prompt Done.
