prompt
prompt Instalando operaciones...
prompt -----------------------------------
prompt
@@scripts/operations/parametros/_/contexto.sql
@@scripts/operations/parametros/_/parametros_automaticos.sql
@@scripts/operations/reporte/gen/listar_significados.sql
@@scripts/operations/reporte/gen/version_sistema.sql
@@scripts/operations/servicio/aut/cambiar_clave.sql
@@scripts/operations/servicio/aut/cambiar_estado_sesion.sql
@@scripts/operations/servicio/aut/cambiar_estado_usuario.sql
@@scripts/operations/servicio/aut/datos_dispositivo.sql
@@scripts/operations/servicio/aut/datos_usuario.sql
@@scripts/operations/servicio/aut/editar_usuario.sql
@@scripts/operations/servicio/aut/generar_otp.sql
@@scripts/operations/servicio/aut/iniciar_sesion.sql
@@scripts/operations/servicio/aut/refrescar_sesion.sql
@@scripts/operations/servicio/aut/registrar_clave.sql
@@scripts/operations/servicio/aut/registrar_dispositivo.sql
@@scripts/operations/servicio/aut/registrar_ubicacion.sql
@@scripts/operations/servicio/aut/registrar_usuario.sql
@@scripts/operations/servicio/aut/tiempo_expiracion_token.sql
@@scripts/operations/servicio/aut/validar_clave_aplicacion.sql
@@scripts/operations/servicio/aut/validar_credenciales.sql
@@scripts/operations/servicio/aut/validar_otp.sql
@@scripts/operations/servicio/aut/validar_permiso.sql
@@scripts/operations/servicio/aut/validar_sesion.sql
@@scripts/operations/servicio/gen/guardar_archivo.sql
@@scripts/operations/servicio/gen/listar_aplicaciones.sql
@@scripts/operations/servicio/gen/listar_barrios.sql
@@scripts/operations/servicio/gen/listar_ciudades.sql
@@scripts/operations/servicio/gen/listar_departamentos.sql
@@scripts/operations/servicio/gen/listar_errores.sql
@@scripts/operations/servicio/gen/listar_paises.sql
@@scripts/operations/servicio/gen/listar_significados.sql
@@scripts/operations/servicio/gen/recuperar_archivo.sql
@@scripts/operations/servicio/gen/recuperar_texto.sql
@@scripts/operations/servicio/gen/significado_codigo.sql
@@scripts/operations/servicio/gen/valor_parametro.sql
@@scripts/operations/servicio/gen/version_servicio.sql
@@scripts/operations/servicio/gen/version_sistema.sql
