[Item1]
Description=nombre_mayusculas_al_insertar
TestScript=nombre_mayusculas_al_insertar.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item2]
Description=apellido_mayusculas_al_insertar
TestScript=apellido_mayusculas_al_insertar.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item3]
Description=nombre_completo_mayusculas_al_insertar
TestScript=nombre_completo_mayusculas_al_insertar.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item4]
Description=nombre_mayusculas_al_actualizar
TestScript=nombre_mayusculas_al_actualizar.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item5]
Description=apellido_mayusculas_al_actualizar
TestScript=apellido_mayusculas_al_actualizar.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK
[Item6]
Description=nombre_completo_mayusculas_al_actualizar
TestScript=nombre_completo_mayusculas_al_actualizar.tst
NewSession=False
Enabled=True
Performance=
Var1Name=result
Var1Enabled=True
Var1Global=False
Var1Type=String
Var1InputValue=
Var1OutputValue=OK

[Notes]
{\rtf1\ansi\deff0\nouicompat{\fonttbl{\f0\fnil Arial;}}
{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
\pard\f0\fs20\lang2058 Tests unitarios del trigger gb_personas\par
}
